Added "The Lurking Fear", "The Silver Key", "The Haunter of the Dark", and "The Thing on the Doorstep"
standardebooks/h-p-lovecraft_short-fiction pull request #12
Opened 2024-03-27 16:41 UTC by HendrikBK

2024-03-27 19:54 UTC, acabal requested changes
We also need to add `<dc:source>` with PG transcriptions and page scans for these. Did you also add them for the other items you recently added? I can't recall.

2024-03-27 19:54 UTC, acabal commented on src/epub/text/pickmans-model.xhtml
> +			<p>It was a colossal and nameless blasphemy with glaring red eyes, and it held in bony claws a thing that had been a man, gnawing at the head as a child nibbles at a stick of candy. Its position w
This is an incorrect change

2024-03-27 20:00 UTC, acabal requested changes

2024-03-27 20:00 UTC, acabal commented on src/epub/text/the-thing-on-the-doorstep.xhtml
> +				<p>By the time he was twenty-five Edward Derby was a prodigiously learned man and a fairly well-known poet and <em>fantasist</em>, though his lack of contacts and responsibilities had slowed down
This is incorrect, `fantaisiste` is a French word, not English emphasis. This should be reverted and changed to `<i xml:lang="fr">`

2024-03-27 20:00 UTC, acabal commented on src/epub/text/the-thing-on-the-doorstep.xhtml
> +				<p>“I had to save myself⁠—I had to, Dan! She’d have got me for good at Hallowmass⁠—they hold a Sabbath up there beyond Chesuncook, and the sacrifice would have clinched things. She’d have got me
Incorrect change, `Sabbat` means a witch's festival, `Sabbath` means a day of rest and worship

2024-03-27 21:51 UTC, HendrikBK commented
The change in "Pickman's Model" was an accident, I just reverted.
I did add source in metadata for the other stories, I just forgot about these ones, they're present now.
I don't understand the issue with "any one" in "The Haunter of the Dark", there doesn't seem to be any change of the kind the section, perhaps you meant another wish?

2024-03-27 21:53 UTC, acabal commented
> The change in "Pickman's Model" was an accident, I just reverted. I did add source in metadata for the other stories, I just forgot about these ones, they're present now. I don't understand the issue with "any one" in "The Haunter of the Dark", there doesn't seem to be any change of the kind the section, perhaps you meant another wish?

`gases born of long decay⁠—anyone of numberless` is in correct

2024-03-28 18:34 UTC, merged

2024-03-28 18:34 UTC, acabal commented
Good work, thanks!